#!/usr/bin/env bash
# Regenerate artifacts/environment.md, SANITIZED BY CONSTRUCTION.
#
# This repository is public. The capture must never emit machine-identifying
# material, so it whitelists the fields that matter for reproducibility rather
# than dumping command output wholesale. In particular:
#
#   - the hostname is never read;
#   - /proc/cmdline is NOT emitted verbatim (it carries the ZFS pool and dataset
#     names on this box). Only the flags that affect NPU behaviour are reported,
#     as present/absent -- `amd_iommu=off` in particular makes the NPU vanish
#     entirely, so its absence is the reproducibility-relevant fact;
#   - the /dev/accel stat line is reduced to mode+owner, dropping the mtime.
#
# Run tools/scan_artifacts.sh afterwards to verify.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=artifacts/environment.md

# NPU-relevant kernel flags, reported by presence rather than by echoing cmdline.
kflags() {
    local cl; cl=$(cat /proc/cmdline)
    for f in amd_iommu iommu amdgpu.gttsize amdttm.pages_limit amdxdna; do
        if grep -qE "(^| )$f(=|\b)" <<<"$cl"; then
            grep -oE "(^| )$f[^ ]*" <<<"$cl" | tr -d ' ' | sed 's/^/  present: /'
        else
            echo "  absent:  $f"
        fi
    done
}

{
echo "# Environment"
echo
echo "Captured: $(date -u +%Y-%m-%dT%H:%M:%SZ) on <redacted-hostname>"
echo "Generated by \`tools/capture_environment.sh\` (sanitized by construction)."
echo
echo '## Hardware'
echo '```'
echo "CPU:      $(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2- | sed 's/^ *//')"
echo "Cores:    $(nproc) threads, $(lscpu | awk -F: '/^Core\(s\) per socket/{gsub(/ /,"",$2);print $2}') cores"
echo "RAM:      $(free -g | awk '/^Mem:/{print $2"Gi"}')"
lspci -nn 2>/dev/null | grep -iE "\[1002:1586\]|\[1022:17f0\]" || true
echo '```'
echo
echo '## OS / kernel'
echo '```'
echo "Distro:   $(. /etc/os-release && echo "$PRETTY_NAME")"
echo "Kernel:   $(uname -r)"
echo "glibc:    $(ldd --version | head -1 | grep -oE '[0-9]+\.[0-9]+$')"
echo '```'
echo
echo 'NPU-relevant kernel flags (cmdline is not emitted; it carries storage identifiers):'
echo '```'
kflags
echo '```'
echo
echo '## NPU driver / firmware'
echo '```'
echo "module:   amdxdna $(modinfo amdxdna 2>/dev/null | awk -F: '/^intree/{gsub(/ /,"",$2);print "(intree="$2")"}')"
echo "device:   $(stat -c '%A %U:%G' /dev/accel/accel0 2>/dev/null) /dev/accel/accel0"
echo "fw:       $(cat /sys/bus/pci/devices/0000:c7:00.1/fw_version 2>/dev/null || echo unknown)"
echo "iommu:    $(ls /sys/class/iommu/ 2>/dev/null | tr '\n' ' ')"
echo "memlock:  $(ulimit -l)"
echo '```'
echo
echo '## XRT'
echo '```'
dpkg -l 2>/dev/null | awk '/libxrt|python3-xrt/{printf "%-20s %s\n", $2, $3}'
echo
xrt-smi examine 2>/dev/null | sed -n '/^XRT/,/^$/p'
xrt-smi examine 2>/dev/null | grep -E "RyzenAI-npu.*aie2p" | sed 's/^ */  /'
xrt-smi examine -r platform 2>/dev/null | grep -E "Total Columns|Power Mode" | sed 's/^ */  /'
echo '```'
echo
echo '## NPU kernel toolchain (offline; not on the runtime path)'
echo '```'
PEANO=$(.venv/bin/pip list 2>/dev/null | awk '/^llvm-aie/{print $2}')
MLIRAIE=$(.venv/bin/pip list 2>/dev/null | awk '/^mlir[-_]aie/{print $2}')
printf "%-10s %s\n" mlir-aie "${MLIRAIE:-not found in .venv}"
printf "%-10s %s\n" peano    "${PEANO:-not found in .venv}"
echo "target     aie2p (--target=aie2p-none-unknown-elf), __AIE_ARCH__ == 21"
echo '```'
echo
echo '## Toolchain'
echo '```'
printf "%-10s %s\n" gcc      "$(gcc --version | head -1)"
printf "%-10s %s\n" clang    "$(clang --version | head -1)"
printf "%-10s %s\n" cmake    "$(cmake --version | head -1)"
printf "%-10s %s\n" ninja    "$(ninja --version)"
printf "%-10s %s\n" python3  "$(python3 --version)"
echo '```'
} > "$OUT"
echo "wrote $OUT"
